version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: itemsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://dev:dev@db:5432/itemsdb
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
